nginx:
  image: nginx:1.16.1-alpine
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - php
  volumes:
    - /code/conf/nginx/conf.d:/etc/nginx/conf.d
    - /code/www:/usr/share/nginx/html

php:
  image: zhou604638018/alpine:php7.2
  container_name: php
  volumes:
    - /code/www:/var/www/html
    - /code/conf/php-fpm.d:/usr/local/etc/php-fpm.d
